Upgraded Moq and Castle.Core
huysentruitw/entity-framework-mock pull request #18
Opened 2020-08-14 17:21 UTC by pwmckee

2020-08-14 18:30 UTC, huysentruitw requested changes

2020-08-14 18:30 UTC, huysentruitw commented on src/EntityFrameworkMock.Moq/EntityFrameworkMock.Moq.csproj
> +    <PackageReference Include="Castle.Core" Version="4.4.1" />
Can we keep the version range, but just change the minimum version? So this version would become: `"[4.4.1, 5.0.0)"`.

2020-08-15 00:07 UTC, pwmckee commented on src/EntityFrameworkMock.Moq/EntityFrameworkMock.Moq.csproj
> +    <PackageReference Include="Castle.Core" Version="4.4.1" />
Oh yes, of course I'll change it when I get back home

2020-08-15 06:42 UTC, merged

2020-08-15 06:42 UTC, huysentruitw commented
Thank you for this PR.