Automapper Fix when using AutoMapper ProjectTo in LINQ query
huysentruitw/entity-framework-mock pull request #8
Opened 2018-11-09 11:23 UTC by michielpeeters

This piece of code fixes the problem when AutoMapper extension ProjectTo is being used.

2018-11-10 09:15 UTC, huysentruitw commented
What is the exact error you're trying to fix here?

2018-11-10 09:16 UTC, huysentruitw requested changes

2018-11-10 09:16 UTC, huysentruitw commented on src/EntityFrameworkMock.Shared/DbAsyncQueryProvider.cs
> +            switch (expression)
A switch should not be needed for only testing one case.

2018-11-10 09:16 UTC, huysentruitw commented on src/EntityFrameworkMock.Shared/DbAsyncQueryProvider.cs
> +        public IQueryable CreateQuery(Expression expression)
Please add one or more unit-tests to cover this change.

2018-11-12 07:23 UTC, michielpeeters commented
You are absoluty right :-) sorry for that! The error which is thrown is:

Unable to cast object of type 'EntityFrameworkMock.DbAsyncEnumerable 1[EntityFrameworkMock.Tests.Models.User] to type System.Linq.IQueryable 1[EntityFrameworkMock.Tests.DbContextMockTests+UserViewModel]'.

And is fixed with this PR. I've added a testcase ofcourse :-).

2018-11-12 16:42 UTC, huysentruitw commented
I'll merge it to the develop branch and do some small changes before merging it to the master branch.

Thanks for this change!

2018-11-12 16:44 UTC, merged

2018-11-12 16:47 UTC, michielpeeters commented
You're welcome!